version: '3.8'

services:
  database:
    container_name: cilist-db
    image: heryfik/cilist-pipeline-db:${GIT_COMMIT_SHORT}
  
  backend:
    image: heryfik/cilist-pipeline-be:${GIT_COMMIT_SHORT}
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - BASE_URL_PORT=5000
      - MYSQL_ROOT_PASSWORD=s3k0l4hd3v0p5
      - DATABASE_USERNAME=people
      - DATABASE_PASSWORD=people
      - DATABASE_DATABASE=people
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
